# Development venv for dinosar development
name: dinosar-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - msgpack-python
  - poetry
  - geopandas
  - pyyaml
  - pip
  - pip:
    - poetry-dynamic-versioning
